"""`mdoctest --init`: scaffold the two files that make a repo self-testing.

Writes a pre-commit hook entry and a GitHub Actions workflow so a project's
Markdown examples get checked on every commit and every PR. Both operations are
idempotent and never clobber existing content: if mdoctest is already wired in,
we say so and leave the file untouched.
"""
from __future__ import annotations

import os
from typing import List, Tuple

from . import __version__

PRECOMMIT_FILE = ".pre-commit-config.yaml"
WORKFLOW_FILE = os.path.join(".github", "workflows", "mdoctest.yml")

_REPO = "https://github.com/ingrid-owusu/mdoctest"


def _precommit_repo_block() -> str:
    return (
        "  - repo: %s\n"
        "    rev: v%s\n"
        "    hooks:\n"
        "      - id: mdoctest\n"
    ) % (_REPO, __version__)


def _new_precommit_file() -> str:
    return "repos:\n" + _precommit_repo_block()


def _workflow_text() -> str:
    return (
        "name: mdoctest\n"
        "\n"
        "# Verify the code and console examples in the docs still produce the\n"
        "# output they claim. Generated by `mdoctest --init`.\n"
        "on:\n"
        "  push:\n"
        "  pull_request:\n"
        "\n"
        "jobs:\n"
        "  docs:\n"
        "    runs-on: ubuntu-latest\n"
        "    steps:\n"
        "      - uses: actions/checkout@v4\n"
        "      - uses: ingrid-owusu/mdoctest@v1\n"
        "        with:\n"
        "          files: README.md\n"
    )


def _ensure_precommit() -> Tuple[str, str]:
    """Return (status, path). status in {created, updated, present}."""
    if not os.path.exists(PRECOMMIT_FILE):
        with open(PRECOMMIT_FILE, "w", encoding="utf-8") as f:
            f.write(_new_precommit_file())
        return "created", PRECOMMIT_FILE

    with open(PRECOMMIT_FILE, "r", encoding="utf-8") as f:
        text = f.read()
    if "ingrid-owusu/mdoctest" in text or "id: mdoctest" in text:
        return "present", PRECOMMIT_FILE

    block = _precommit_repo_block()
    if "repos:" in text:
        # Append after the last line, ensuring a trailing newline first.
        if not text.endswith("\n"):
            text += "\n"
        text += block
    else:
        # File exists but has no `repos:` key; prepend a fresh section.
        prefix = text
        if prefix and not prefix.endswith("\n"):
            prefix += "\n"
        text = prefix + _new_precommit_file()
    with open(PRECOMMIT_FILE, "w", encoding="utf-8") as f:
        f.write(text)
    return "updated", PRECOMMIT_FILE


def _ensure_workflow() -> Tuple[str, str]:
    if os.path.exists(WORKFLOW_FILE):
        return "present", WORKFLOW_FILE
    os.makedirs(os.path.dirname(WORKFLOW_FILE), exist_ok=True)
    with open(WORKFLOW_FILE, "w", encoding="utf-8") as f:
        f.write(_workflow_text())
    return "created", WORKFLOW_FILE


def init(emit=print) -> int:
    """Scaffold pre-commit + GitHub Actions wiring. Returns an exit code."""
    results: List[Tuple[str, str]] = [_ensure_precommit(), _ensure_workflow()]
    verb = {
        "created": "created",
        "updated": "updated",
        "present": "already configured",
    }
    for status, path in results:
        emit("mdoctest: %s %s" % (verb[status], path))

    if all(s == "present" for s, _ in results):
        emit("mdoctest: nothing to do — this repo is already wired up.")
    else:
        emit("")
        emit("Next steps:")
        emit("  1. pre-commit install        # run the hook on every commit")
        emit("  2. mdoctest                   # check your docs right now")
        emit("  3. commit the two files above # CI will check every PR")
    return 0
